### ISSUE TITLE
OSX compilation issues

### ISSUE THREAD

**Issue by thefosk** [gvvaughan/lyaml#12]
When installing the library on OSX, at one point the output says:

```
libtool: warning: remember to run 'libtool --finish /usr/lib/luarocks/rocks/lyaml/6.0-1/lib/lua/5.1'
```

Executing this command generates the following error:

```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `-' in: --finish
```

And prevents the library from working:

```
/usr/local/share/lua/5.1/lub/Autoload.lua:28: module 'yaml.version' not found:
	no field package.preload['yaml.version']
	no file './yaml/version.lua'
	no file '/usr/local/share/lua/5.1/yaml/version.lua'
	no file '/usr/local/share/lua/5.1/yaml/version/init.lua'
	no file '/usr/local/lib/lua/5.1/yaml/version.lua'
	no file '/usr/local/lib/lua/5.1/yaml/version/init.lua'
	no file './yaml/version.so'
	no file '/usr/local/lib/lua/5.1/yaml/version.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no module 'yaml.version' in file '/usr/local/lib/lua/5.1/yaml.so'
/usr/local/share/lua/5.1/lub/Autoload.lua:28: module 'yaml.emitter' not found:
	no field package.preload['yaml.emitter']
	no file './yaml/emitter.lua'
	no file '/usr/local/share/lua/5.1/yaml/emitter.lua'
	no file '/usr/local/share/lua/5.1/yaml/emitter/init.lua'
	no file '/usr/local/lib/lua/5.1/yaml/emitter.lua'
	no file '/usr/local/lib/lua/5.1/yaml/emitter/init.lua'
	no file './yaml/emitter.so'
	no file '/usr/local/lib/lua/5.1/yaml/emitter.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no module 'yaml.emitter' in file '/usr/local/lib/lua/5.1/yaml.so'
lua: /usr/local/share/lua/5.1/lyaml.lua:227: attempt to call field 'emitter' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/lyaml.lua:227: in function 'Dumper'
	/usr/local/share/lua/5.1/lyaml.lua:252: in function 'dump'
	/tmp/test.lua:2: in main chunk
	[C]: ?
```

**Comment by gvvaughan** [comment]
Does it work if you **don't** run `libtool --finish`?  If so, then the real issue is that the generated in-tree libtool script should not tell you to run your Apple libtool binary.  Please report that upstream to bug-libtool@gnu.org -- I'm no longer maintaining GNU Libtool, so I'm not in a position to fix it myself, sorry!

By way of explanation: `libtool` on Mac OS X is an entirely different thing to _GNU Libtool_, and I wouldn't be surprised if the former does indeed behave unexpectedly when called with unsupported arguments intended for the latter.  I expect it would have worked just fine if you had instead run:

```bash
./libtool --finish /usr/lib/luarocks/rocks/lyaml/6.0-1/lib/lua/5.1
```

Or equivalently, assuming you have a sufficiently well configured GNU libtool installed in your PATH:

```bash
glibtool --finish /usr/lib/luarocks/rocks/lyaml/6.0-1/lib/lua/5.1
```

...which is a NOP in both cases, because Mac OS has `$finish_cmds` set to the empty string:

```bash
glibtool --config | grep finish_cmds=
finish_cmds=""
```

HTH!

**Comment by thefosk** [comment]
It doesn't work either way, with or without running the command (which ultimately fails to run).

**Comment by gvvaughan** [comment]
I build and run regression tests for lyaml on LuaJIT, Lua 5.1, 5.2 and 5.3 with every commit (you can see where the output differs from your by clicking the 'build:passing' badge on the lyaml github front page to work out where your build has diverged from a working one), so I'd be surprised to find a bug that prevents lyaml from loading in the lyaml code itself.

It looks like you are using some other package to load instead of the Lua provided package require command:

```
/usr/local/share/lua/5.1/lub/Autoload.lua:28: [...]
```

Try running a vanilla lua interpreter with the LUA_PATH and LUA_CPATH containing just the directory containing the installed lyaml Lua sources, and the yaml.so library respectively to see whether `lub` is messing up your package loader.

There is definitely something strange about your installation too, because in addition to the additional Autoloader module loader you're using, it seems as though the lyaml.lua is loading, because it gets `yaml.version` from the yaml.so library, and that is either failing to load, or not available along the paths tried by your Autoloader.

Hope that gives you some help in tracking down the error.

Cheers,
Gary
