### ISSUE TITLE
Error on build in last version

### ISSUE THREAD

**Issue by Romaboy** [gvvaughan/lyaml#20]
```
build-aux/luke:120: attempt to concatenate local 'found' (a nil value)
stack traceback:
        build-aux/luke:120: in function 'check_executable_in_path'
        build-aux/luke:197: in function 'block'
        build-aux/luke:432: in function 'dropuntil'
        build-aux/luke:197: in function 'block'
        build-aux/luke:432: in function 'dropuntil'
        build-aux/luke:210: in function 'configure'
        build-aux/luke:220: in function 'config_ldoc'
        build-aux/luke:244: in function 'build_modules'
        build-aux/luke:254: in function 'main'
        build-aux/luke:618: in main chunk
        [C]: at 0x00405060
```
Oh, I don't understand, no tabs, for god's sake, where are tabs?
```lua
local function check_executable_in_path(L,env,config,prog)local PATH=concat(bindirs(config.bindir))..getenv('PATH')local found=dropuntil(gmatch(PATH,'[^:]+'),function(path)local progpath=path..'/'..prog
return with(File(progpath,'r'),function(h)return isfile(h.context)and progpath or nil
end)end)L.debug('found '..found)return found~=nil
end
```
Thanks for useful module, but this code is horror.
`L.debug('found '..found)return found~=nil` here `found` is nil and this causes an error.

**Comment by gvvaughan** [comment]
Thanks for the report.

LOL. Sorry dude! The tabs are here:

https://github.com/gvvaughan/luke/tree/rockspec-reboot?files=1

The distribution is minified into a single file.

This bug is fixed in the latest version of luke if you want to fix your version right away. I'll make another release this weekend to pick up the changes though; thanks for the reminder.

I think I should add a url for the luke repo to the top of the minified version to save other folks from the tab shock.

**Comment by Romaboy** [comment]
Finally I found the way to install it!
When installing from luarocks there is a stupid error, so I cloned repo and then
`luarocks install lyaml-git-1.rockspec`
It's almost ok, but `require 'lyaml'` don't work, and instead of it `require 'lyaml.init'` works.
It's most popular yaml lib in luarocks, please, make life of it's users little bit easier.

**Comment by gvvaughan** [comment]
Glad you worked around the problem, and sorry for the delay: I wanted to fix an additional issue in luke that affects luaposix too -- now done, so I pushed a new release, 6.1.3 up to luarocks.org which works on the Ubuntu machines in Travis CI, and all 3 of my architectures and OSes here.  I haven't announced it to the list yet, in case you still have problems with it.

The issue with needing to `require 'lyaml.init'` is because you haven't set your LUA_PATH correctly, or your luarocks is misconfigured.  It should contain both of e.g.:

```bash
$ luarocks path
export LUA_PATH='/home/gary/.luarocks/share/lua/5.3/?.lua;/home/gary/.luarocks/share/lua/5.3/?/init.lua;[[etc]]'
```

It looks like you are missing at least one of the `.../?/init.lua` elements from yours?

Closing for now, but feel free to open a new issue if you still have a problem with the latest release.  Otherwise I'll make an official release announcement in a few more days.

Cheers,
Gary

**Comment by Romaboy** [comment]
> It looks like you are missing at least one of the .../?/init.lua elements from yours?

Yes, but seems like there is no LUA_PATH standard saying about .../?/init.lua, many other modules works fine.
Better approach:
```lua
-- /path/to/lua/lib/lyaml.lua
return require("lyaml.init")
```
Thanks for maintaining!
