### ISSUE TITLE
How to dump empty object and empty array?

### ISSUE THREAD

**Issue by ichaozai** [gvvaughan/lyaml#47]
```lua
local lyaml = require "lyaml"

print(lyaml.dump({{array = {}, object = {}}}))
```
output:
```
---
array: []
object: []
...
```

Lua uses table as array. How to distinguish an empty table and an empty array?

**Comment by gvvaughan** [comment]
If there are no contents inside, does it matter? Perhaps you can already tell by the name of the key or some other clue from the document structure if you have specific documents.

Otherwise, If you really need to do this for generality or roundtripping or similar, then you’ll need to tweak the dumper code to write a sentinel value for one or the other or both - much the way that it already handles nil.

The best place to start is with a copy of `dumper_mt` in lib/lyaml/init.lua and then tweak accordingly.

**Comment by ichaozai** [comment]
It does matter if I process the YAML in static type languages, or convert YAML to JSON.
I can make a PR to do this like [lua-cjson](https://github.com/openresty/lua-cjson/#empty_array_mt).
