### ISSUE TITLE
Purpose of nested table required for dumping?

### ISSUE THREAD

**Issue by GUI** [gvvaughan/lyaml#7]
I was curious why, when dumping a table, I have to wrap it inside another table. For example, this returns an empty string:

```
> print(lyaml.dump({ foo = "bar" }))

```

Whereas if I wrap my table inside another, then I get the expected output:

```
> print(lyaml.dump({{ foo = "bar" }}))
---
foo: bar
…
```

This seems confusing since it means I can't actually use `lyaml.dump` on a table previously parsed with `lyaml.load` without manually adding this extra wrapper table:

```
> print(lyaml.dump(lyaml.load("foo: bar")))

> print(lyaml.dump({ lyaml.load("foo: bar") }))
---
foo: bar
…
```

I would expect that first example to work, since intuitively it seems like I should be able to dump something that the library loads without tweaking the object.

So my primary question is whether or not this extra table is purposeful in the lyaml dump API. If it is, then it's easy enough to workaround, but I might recommend documenting it more clearly in the README (I had to look at the test suite to understand this). I'd be happy to submit a pull request with some documentation updates, but I first just wanted to make sure this design was intended when dumping tables.

**Comment by gvvaughan** [comment]
Hi Nick,

Thanks for the feed back.  You have found a wart in the API for sure.  The reason for the wrapping table is to support multi-document files, where the outer table represents the file, and each inner table is one of the YAML documents contained within it.

I tried to simplify the loader by stripping the outer document container table for single document files, but couldn't do the same with the dumper by default as that would lead to potential errors when trying to dump a single document made entirely of Lua tables, versus a multi-document file.

In hindsight, the simplification was probably a mistake, though I don't really think about it anymore because Lua let's me write your last example like this:

```lua
print (lyaml.dump {lyaml.load "foo: bar"})
```

Pull-requests to make this less confusing are most welcome though!

Cheers,
Gary
