### ISSUE TITLE
YAML merge key not working

### ISSUE THREAD

**Issue by mrk21** [gvvaughan/lyaml#8]
```yaml
---
default: &default
  value1: 1
  value2: 2

hoge:
  <<: *default
  value3: 3
```

When the above YAML file parsed, it should be the Lua table shown below:

```lua
{
  default = {
    value1 = 1,
    value2 = 2
  },
  hoge = {
    value1 = 1,
    value2 = 2,
    value3 = 3
  }
}
```

However, it will be the Lua table shown below actually:

```lua
{
  default = {
    value1 = 1,
    value2 = 2
  },
  hoge = {
    ['<<'] = {
      value1 = 1,
      value2 = 2
    },
    value3 = 3
  }
}
```

**Comment by gvvaughan** [comment]
I've never seen the '<<' token treated specially, nor can I find a reference to it in the YAML 1.1 or 1.2 specifications or grammars.  Can you point me at the relevant documentation please?

**Comment by mrk21** [comment]
@gvvaughan YAML merge key is not a core function of YAML format, so it does not exist on YAML specifications; it is implemented by YAML tags stipulated by [yaml.org](http://yaml.org/type/merge.html).

It is a language-Independent tag, and it is not tags depended to specific languages such as `!ruby/array`.

**See**

* [Merge Key Language-Independent Type for YAML™ Version 1.1](http://yaml.org/type/merge.html)
* [Language-Independent Types for YAML™ Version 1.1](http://yaml.org/type/)

**Comment by gvvaughan** [comment]
Thanks, this also solves a problem I have been mulling over with Specl too :)

The changeset as committed only supports merging alias maps into the surrounding map.  It's not clear from the specification whether literal maps should be merged too.  @mrk21 Do you know how other implementations behave?

I also went ahead and improved parsing of null, bool, float and int according to some of the other types specified from the page you linked.  Thanks again!  I'm not yet convinced that having bare 'y' or bare 'n' be implicit boolean true and false though:

```yaml
location:
  - x: 221
  - y: 76
```

becomes:

```lua
{ location = { x = 221, true = 76 } } 
```

I'm tempted to coerce only 'true' and 'false' strings to implicit booleans, and require the '!!bool' tag for the other variants. @mrk21 Do you know how other implementations handle this (because I'd like to be compatible)?

**Comment by gvvaughan** [comment]
@GUI as you are more familiar with Ruby than I (that is, more than zero familiarity!), do you know how its YAML implementation handles conversion of implicit booleans?  I'm not happy with the automatic 'y' value loading as boolean among others, for obvious reasons.

I have a half baked patch to add an API for queueing implicit conversion functions when the parser/dumper match given patterns for finer grain control over how it works, but I'd like the default to be compatible with the behaviour of Ruby's YAML implementation (without having to learn enough Ruby to figure it out from first principles by myself!).  Any clues much appreciated...

**Comment by GUI** [comment]
@gvvaughan: Huh, I hadn't even realized how loose the boolean parsing was in YAML's spec. Interesting! It looks like despite `y/n` appearing in the [yaml 1.0/1.1 spec](http://yaml.org/type/bool.html), Ruby's parser ignores `y` and `n` values and treats them as strings. It parses all the other boolean values (`yes/no, true/false, on/off`) as boolean values though. Here's their test suite: https://github.com/tenderlove/psych/blob/master/test/psych/test_boolean.rb

Python's primary YAML library seems to take the exact same approach (yes/no, true/false, on/off are all treated as booleans, but not y/n). This [thread](http://pyyaml.org/ticket/26) provides a bit more context on the removal of y/n parsing.

And because this got me curious, here's some additional [discussion](http://sourceforge.net/p/yaml/mailman/message/12308094/) in the yaml-core mailing list about this exact issue. It seems like the general consensus was that treating `y/n` as strings is fine and the spec is really more of a recommendation. So I think you'd be in broad company if you want to treat `y/n` as strings and not booleans.

Interestingly, when I tested [js-yaml](https://github.com/nodeca/js-yaml) on nodejs I noticed it only parses `true/false` as booleans and nothing else. But I think this might be related to the fact that js-yaml is aiming for YAML 1.2 compatibility which has simplified the spec to only include [`true/false`](http://www.yaml.org/spec/1.2/spec.html#id2803629) (since their aiming for more JSON parity with YAML 1.2). So that approach also seems valid (and is personally all I ever expected from YAML parsing), but it also seems like most YAML 1.1 parsers out there (which is what libyaml targets) still include the other boolean values (`yes/no, on/off`).

Anyway, hope some of that helps!

**Comment by gvvaughan** [comment]
That is all very useful, thanks.  Especially the pointer to the ruby yaml parser specs, which I can reference once I find time to support some of the other missing tags.

In the mean time, I've fixed lyaml's implicit booleans to behave sanely like Ruby does.

I've also added support for injecting your own implicit scalar and tagged scalar parsing, so I think there's enough to justify a new release over the weekend!
